# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191025_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
